# Generated by Django 4.2.7 on 2023-11-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100)),
                ('coordinate_x', models.IntegerField()),
                ('coordinate_y', models.IntegerField()),
                ('town_hall', models.IntegerField()),
                ('barracks', models.IntegerField()),
                ('pikemen', models.IntegerField()),
                ('halberdiers', models.IntegerField()),
            ],
        ),
    ]
