# Generated by Django 4.2.7 on 2023-11-08 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plemiona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='village',
            name='barracks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='village',
            name='coordinate_x',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='village',
            name='coordinate_y',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='village',
            name='halberdiers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='village',
            name='pikemen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='village',
            name='town_hall',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_name',
            field=models.CharField(default='New Village', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('coordinate_x', 'coordinate_y')},
        ),
    ]
