# Generated by Django 4.2.7 on 2023-11-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plemiona', '0004_village_archer_cavalary_village_heavy_cavalary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='archer_cavalary',
            new_name='archer_cavalry',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='heavy_cavalary',
            new_name='heavy_cavalry',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='light_cavalary',
            new_name='light_cavalry',
        ),
    ]
