# Generated by Django 4.2.7 on 2023-12-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plemiona', '0005_rename_archer_cavalary_village_archer_cavalry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='forge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='market',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='palace',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='population_army',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='population_buildings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='population_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='stable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='wall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='workshop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='village',
            name='farm',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='village',
            name='granary',
            field=models.IntegerField(default=1),
        ),
    ]
