# Generated by Django 4.2.7 on 2023-12-04 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plemiona', '0006_village_cache_village_forge_village_market_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(max_length=100)),
                ('attacker', models.CharField(max_length=100)),
                ('defender', models.CharField(max_length=100)),
                ('village_attacker_name', models.CharField(max_length=100)),
                ('village_defender_name', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('village_attacker_coordinates_x', models.IntegerField()),
                ('village_attacker_coordinates_y', models.IntegerField()),
                ('village_defender_coordinates_x', models.IntegerField()),
                ('village_defender_coordinates_y', models.IntegerField()),
                ('details', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='plemiona.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
