# Generated by Django 4.2.7 on 2023-12-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plemiona', '0008_message_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
    ]
