# Generated by Django 4.2.7 on 2023-12-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plemiona', '0009_remove_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='brak tresci'),
        ),
    ]
