# Generated by Django 4.2.7 on 2023-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plemiona', '0015_answers_message_rename_message_topic_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic_message',
            old_name='is_read',
            new_name='is_readed_receiver',
        ),
        migrations.AddField(
            model_name='topic_message',
            name='is_readed_sender',
            field=models.BooleanField(default=True),
        ),
    ]
