# Generated by Django 4.2.7 on 2023-12-11 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plemiona', '0016_rename_is_read_topic_message_is_readed_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='attacker',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='defender',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='village_attacker_coordinates_x',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='village_attacker_coordinates_y',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='village_attacker_name',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='village_defender_coordinates_x',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='village_defender_coordinates_y',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='village_defender_name',
        ),
        migrations.AddField(
            model_name='reports',
            name='attacker_army',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reports',
            name='attacker_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attacker_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='defender_army',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reports',
            name='defender_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defender_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reports',
            name='village_attacker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attacker_village_reports', to='plemiona.village'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='village_defender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='defender_village_reports', to='plemiona.village'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reports',
            name='result',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='village',
            name='clay',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='village',
            name='iron',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='village',
            name='wood',
            field=models.FloatField(default=1000),
        ),
    ]
