# Generated by Django 4.2.7 on 2023-12-11 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plemiona', '0017_remove_reports_attacker_remove_reports_defender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reports',
            name='details',
            field=models.CharField(default='brak', max_length=1000),
        ),
    ]
