army_data = {
    "pikemen": {"wood": 50, "clay": 30, "iron": 10, "recruit_time1": 240, "people_needed": 1, "attack": 10,
                "defense_infantry": 15, "defense_cavalry": 45, "defense_archer": 20, "payload": 25, "speed": 18,
                "attack_type": "infantry", "defense_preference": [2, 3, 1]},
    "halberdiers": {"wood": 30, "clay": 30, "iron": 70, "recruit_time1": 360, "people_needed": 1, "attack": 25,
                    "defense_infantry": 50, "defense_cavalry": 15, "defense_archer": 45, "payload": 15, "speed": 22,
                    "attack_type": "infantry", "defense_preference": [1, 3, 2]},
    "axeman": {"wood": 60, "clay": 30, "iron": 40, "recruit_time1": 300, "people_needed": 1, "attack": 40,
               "defense_infantry": 10, "defense_cavalry": 5, "defense_archer": 10, "payload": 10, "speed": 18,
               "attack_type": "infantry", "defense_preference": [1, 3, 2]},
    "archer": {"wood": 100, "clay": 30, "iron": 60, "recruit_time1": 540, "people_needed": 1, "attack": 15,
               "defense_infantry": 50, "defense_cavalry": 40, "defense_archer": 5, "payload": 10, "speed": 18,
               "attack_type": "archer", "defense_preference": [1, 2, 3]},
    "light_cavalry": {"wood": 125, "clay": 100, "iron": 250, "recruit_time1": 1200, "people_needed": 4, "attack": 130,
                      "defense_infantry": 30, "defense_cavalry": 40, "defense_archer": 30, "payload": 80, "speed": 10,
                      "attack_type": "cavalry", "defense_preference": [2, 1, 3]},
    "archer_cavalry": {"wood": 250, "clay": 30, "iron": 150, "recruit_time1": 1600, "people_needed": 5, "attack": 120,
                       "defense_infantry": 40, "defense_cavalry": 30, "defense_archer": 50, "payload": 50, "speed": 10,
                       "attack_type": "archer", "defense_preference": [3, 1, 2]},
    "heavy_cavalry": {"wood": 200, "clay": 150, "iron": 600, "recruit_time1": 2000, "people_needed": 6, "attack": 150,
                      "defense_infantry": 200, "defense_cavalry": 80, "defense_archer": 180, "payload": 50, "speed": 11,
                      "attack_type": "cavalry", "defense_preference": [1, 3, 2]}
}
